const express = require('express');
const r = express.Router();
const { protect, adminOnly } = require('../middleware/auth');
const { getDashboardStats, getAllUsers, updateUser, getAllDisputes, resolveDispute, getActivityLogs, getPlatformAnalytics, getAprilToNowAnalytics, getAllJobs, getFraudAlerts, suspendUserForFraud, updateAIRankingWeights, getAIRankingWeights, deleteJob } = require('../controllers/adminController');
r.get('/stats', protect, adminOnly, getDashboardStats);
r.get('/users', protect, adminOnly, getAllUsers);
r.put('/users/:id', protect, adminOnly, updateUser);
r.get('/disputes', protect, adminOnly, getAllDisputes);
r.put('/disputes/:id/resolve', protect, adminOnly, resolveDispute);
r.get('/logs', protect, adminOnly, getActivityLogs);
r.get('/analytics', protect, adminOnly, getPlatformAnalytics);
r.get('/analytics/april-to-now', protect, adminOnly, getAprilToNowAnalytics);
r.get('/jobs', protect, adminOnly, getAllJobs);
r.delete('/jobs/:id', protect, adminOnly, deleteJob);
r.get('/fraud', protect, adminOnly, getFraudAlerts);
r.post('/fraud/:id/suspend', protect, adminOnly, suspendUserForFraud);
r.get('/ai-ranking/weights', protect, adminOnly, getAIRankingWeights);
r.put('/ai-ranking/weights', protect, adminOnly, updateAIRankingWeights);
module.exports = r;
